version: '3.8'

services:
  gigaset-weather:
    image: uneubauer/gigaset-infodienst:latest
    container_name: gigaset-weather-server
    restart: unless-stopped
    ports:
      - "8100:8080"
    volumes:
      # Verhindert, dass der Wetter-Cache bei Container-Updates gelöscht wird
      - ./WEB-INF:/app/WEB-INF
      
      # NEU: Spiegelt den lokalen 'img'-Ordner direkt in den Container
      - ./public/img:/app/public/img
      
      # Die System-Uhrzeit des Host-Systems wird als Volume durchgereicht
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_ENV=production
      - TZ=Europe/Berlin