version: '3.8'

services:
  gigaset-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gigaset-wetter-container
    ports:
      - "8100:8081" # Mappt Port 8100 deines Heimservers auf den internen Node-Port
    environment:
      - PORT=80
    volumes:
      - /home/docker/gigaset-data:/app/WEB-INF
      # --- NEU: Verknüpft deinen lokalen Bilder-Ordner mit dem public/img Ordner im Container ---
      - /home/docker/gigaset-images:/app/public/img
    restart: always